version: '3'
services:
  chatbot_vendedor:
    build:
      context: ./   # Ruta al directorio donde se encuentra el Dockerfile
      dockerfile: Dockerfile   # Nombre del Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bot_sessions:/app/bot_sessions
    working_dir: /app
    restart: always